# Generated by Django 2.1.3 on 2018-12-07 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100, verbose_name='Nom de la classe')),
            ],
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=100)),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('lieu_naissance', models.CharField(max_length=100, verbose_name='Lieu de naissance')),
                ('sexe', models.CharField(choices=[('F', 'Femme'), ('H', 'Homme')], max_length=1)),
                ('date_arrivee', models.DateField(auto_now_add=True, verbose_name="Date d'arrivée")),
                ('ancienne_ecole', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ancienne école')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionclasse.Classe')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mensualite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_paid', models.BooleanField(default=False)),
                ('mois_paye', models.CharField(choices=[('janvier', 'janvier'), ('fevrier', 'février'), ('mars', 'mars'), ('avril', 'avril'), ('mai', 'mai'), ('juin', 'juin'), ('juillet', 'juillet'), ('aout', 'août'), ('septembre', 'septembre'), ('octobre', 'octobre'), ('novembre', 'novembre'), ('decembre', 'decembre')], max_length=30, verbose_name='Mois payé')),
                ('date_paye', models.DateField(verbose_name='Date de paiement')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionclasse.Eleve')),
            ],
        ),
        migrations.CreateModel(
            name='Tuteur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=100)),
                ('profession', models.CharField(blank=True, max_length=100, null=True)),
                ('telephone', models.IntegerField(null=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='eleve',
            name='tuteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionclasse.Tuteur', verbose_name='Son/Sa tuteur/tutrice'),
        ),
    ]
