# Generated by Django 2.1.3 on 2018-12-07 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclasse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='tuteur',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='gestionclasse.Tuteur', verbose_name='Son/Sa tuteur/tutrice'),
        ),
    ]
