# Generated by Django 2.1.3 on 2018-12-07 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclasse', '0003_auto_20181207_1228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensualite',
            options={'ordering': ['date_paye'], 'verbose_name': 'Mensualité'},
        ),
    ]
