# Generated by Django 2.1.3 on 2018-12-07 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclasse', '0005_auto_20181207_2010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eleve',
            options={'verbose_name': 'Élève'},
        ),
        migrations.AddField(
            model_name='eleve',
            name='telephone',
            field=models.IntegerField(null=True, unique=True, verbose_name='Téléphone du tuteur'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='tuteur',
            field=models.CharField(default=2, max_length=100, verbose_name='Son/Sa tuteur/tutrice'),
            preserve_default=False,
        ),
    ]
