# Generated by Django 2.1.3 on 2018-12-07 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclasse', '0006_auto_20181207_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='tuteur',
            field=models.CharField(default='Aucun', max_length=100, verbose_name='Son/Sa tuteur/tutrice'),
        ),
    ]
