# Generated by Django 2.1.3 on 2018-12-08 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclasse', '0007_auto_20181207_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='telephone',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Téléphone du tuteur'),
        ),
    ]
