# Generated by Django 2.1.3 on 2018-12-08 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclasse', '0008_auto_20181208_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='ancienne_ecole',
            field=models.CharField(blank=True, default='-', max_length=100, null=True, verbose_name='Ancienne école'),
        ),
    ]
