# Generated by Django 2.1.3 on 2018-12-10 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclasse', '0009_auto_20181208_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='date_arrivee',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'arrivée"),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='sexe',
            field=models.CharField(choices=[('F', 'F'), ('H', 'H')], max_length=1),
        ),
        migrations.AlterField(
            model_name='mensualite',
            name='date_paye',
            field=models.DateField(auto_now_add=True, verbose_name='Date paiment'),
        ),
        migrations.AlterField(
            model_name='mensualite',
            name='eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensualites', to='gestionclasse.Eleve'),
        ),
        migrations.AlterField(
            model_name='mensualite',
            name='mois_paye',
            field=models.CharField(choices=[('janvier', 'janvier'), ('fevrier', 'février'), ('mars', 'mars'), ('avril', 'avril'), ('mai', 'mai'), ('juin', 'juin'), ('juillet', 'juillet'), ('octobre', 'octobre'), ('novembre', 'novembre'), ('decembre', 'decembre')], max_length=30, verbose_name='Mois payé'),
        ),
    ]
