# Generated by Django 2.1.3 on 2018-12-10 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclasse', '0010_auto_20181210_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='sexe',
            field=models.CharField(choices=[('F', 'F'), ('M', 'M')], max_length=1),
        ),
    ]
