# Generated by Django 2.1.3 on 2018-12-28 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclasse', '0012_auto_20181228_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='telephone',
            field=models.IntegerField(blank=True, null=True, verbose_name='Téléphone du tuteur'),
        ),
    ]
