# Generated by Django 2.1.3 on 2018-12-30 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclasse', '0013_auto_20181228_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='telephone',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Téléphone du tuteur'),
        ),
    ]
