# Generated by Django 2.1.3 on 2018-12-30 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclasse', '0014_auto_20181230_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='telephone',
            field=models.IntegerField(blank=True, null=True, verbose_name='Téléphone du tuteur'),
        ),
    ]
