# Generated by Django 2.1.3 on 2018-12-30 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionclasse', '0015_auto_20181230_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='libelle',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nom de la classe'),
        ),
    ]
